# add = adicionar
# opts = options (opções)
# "As configurações abaixo são para o Pytest."
# Este comando define opções globais do pytest para todos os testes do projeto.
# Explicação detalhada de cada opção:
#
# --alluredir=allure-results
#     Define o diretório onde os resultados do teste serão salvos para o Allure.
#     Esses arquivos serão usados para gerar o relatório interativo.
#
# --reruns 2
#     Se algum teste falhar, ele será reexecutado até 2 vezes automaticamente.
#     Isso ajuda a reduzir falsos negativos causados por instabilidades temporárias.
#
# -v
#     Ativa o modo verbose, mostrando informações detalhadas de cada teste
#     durante a execução no terminal.
#
# -n 4
#     Executa os testes em paralelo usando 4 threads/processos (pytest-xdist),
#     acelerando a execução de múltiplos testes.
#
# Resumo:
# - Essas opções juntas permitem gerar relatórios, reexecutar testes instáveis,
# ver logs detalhados e acelerar a execução de testes em paralelo.

[pytest]
addopts = --alluredir=allure-results -v -n 4 --reruns 2
